services:
  core-auth:
    image: core-auth
    container_name: core-auth
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    networks:
      - core-net
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - core-net

volumes:
  sqlserver_data:
    
networks:
  core-net:
    driver: bridge